### ISSUE TITLE
Possibility to reset pattern length to 16 steps

### ISSUE THREAD

**Issue by manuelzi** [tsointsoin/x0xb0x-MarOS15#2]
In Edit mode it's possible to decrease the pattern length by selecting the step after the last step and pressing REST+ACCENT+SLIDE. After storing the pattern with fewer steps I couldn't find a way to increase it to 16 steps again.

**Comment by tsointsoin** [comment]
I am not using this operating system anymore, this repository was created so people could make a fork and improve the  code. Try to ask people in the original Adafruit thread (https://forums.adafruit.com/viewtopic.php?f=13&t=33914).
I suggest using n0nx0x if you want a more "303" experience, although it doesn't seem to be open-source.
